supabase/storage-py

storage3/_async/file_api.py, storage3/_sync/file_api.py
Fix double `/` referenced in [issue #261](https://github.com/supabase-community/supabase-py/issues/261#issue-1353071612). Fixed both in async and sync codebases.
=> Justinbarak patch 1

poetry.lock, pyproject.toml
We previously restricted httpx from 0.19-0.22 but a vulnerability has been discovered in these versions(see Security tab and we need to bump to 0.23 to fix the vulnerability across the board.
=> chore: bump httpx to 0.23

poetry.lock, pyproject.toml, storage3/utils.py
bump version to use 0.3.5  which makes use of httpx `0.23.0`
=> chore: bump storage version

.github/workflows/ci.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml, storage3/utils.py
=> chore: bump version and lockfile

storage3/types.py
An update to the [supabase/storage-api](https://github.com/supabase/storage-api/pull/277) introduced new types `file_size_limit` and `allowed_mime_types`
Pr fixes error:
```
!!! TypeError: __init__() got an unexpected keyword argument 'file_size_limit'
```
=> fix: added missing types

pyproject.toml, storage3/utils.py
branch name is incorrect, version is actually 0.5.2
=> chore: bump version to 0.5.2

storage3/_async/file_api.py, storage3/_sync/file_api.py
It simply update the function prototype of `upload` to type correctly the file argument
The upload function implements the management of Bytes/IO-like buffers, but the types of the functions doesn't allow their use.
=> Fix bad typing on upload functions

storage3/_async/bucket.py, storage3/_sync/bucket.py, storage3/types.py, tests/_async/test_client.py, tests/_sync/test_client.py
As part of #84 , this PR adds:
- options to set `file_size_limit` and `allowed_mime_types` while creating a bucket
- a new `update_bucket` method that can set these attributes to existing buckets
Corresponding storage-js PR: supabase/storage-js#151
=> feat: bucket level file controls and an update_bucket method

storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py, tests/_async/test_client.py, tests/_sync/test_client.py
=> feat: created functions to get multiple signed URLs.

.github/workflows/ci.yml
Bug fix for semantic release as it's currently borked.
Python semantic release no longer has a master branch so the CI/CD breaks
I've pointed to the main branch of python semantic release and CI/CD should be fixed now
=> Fix semantic releaase workflow

storage3/utils.py
test if workflow is dependent on pypi permissions
=> feat: bump version

storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py
Make "download" key optional for create_signed_url; without this passing {} as the options argument would make the static type-checker complain
=> fix: make download key optional

.pre-commit-config.yaml, docs/api/types.rst, storage3/_async/file_api.py, storage3/_sync/file_api.py
Previously, user set "cache control" was only being passed as a header. This resulted in the cache-control not being properly set after upload.
This PR sends it also as part of form data like [storage-js does](https://github.com/supabase/storage-js/blob/fa44be8156295ba6320ffeff96bdf91016536a46/src/packages/StorageFileApi.ts#L89)
Note: ~~looks like pre-commit isn't happy with the changelog again~~ fixed
=> fix: send cache-control as form data

storage3/_async/file_api.py, storage3/_sync/file_api.py, tests/_async/test_client.py, tests/_sync/test_client.py
Add missing update feature
No update feature for files
Update feature for files
Need to update the docs site to include an example
=> feat: add update existing file function

storage3/_async/file_api.py, storage3/_sync/file_api.py
Seeks to fix https://github.com/supabase-community/supabase-py/issues/721 
We should probably add better error handling at some point - went with a minimal fix for now
=> fix: handle json decode error when there's no json response (e.g. on 403)

.pre-commit-config.yaml, storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py
This is to address issue https://github.com/supabase-community/supabase-py/issues/693.  Documentation said we could use the upsert option, but user would have to specify x-upsert.  
I also updated pre-commit hooks as the version of autoflake is old enough to still require distutils which no longer exists in python 3.12.  
Old behavior code:
```
with open(filepath, 'rb') as f:
supabase.storage.from_("bucket_name").update(file=f, path=path_on_supastorage, file_options={"cache-control": "3600", "upsert": "true"})
```
would not pass along the upsert option to server side.
New behavior:
```
with open(filepath, 'rb') as f:
supabase.storage.from_("bucket_name").update(file=f, path=path_on_supastorage, file_options={"cache-control": "3600", "upsert": "true"})
```
Is passed along as x-upsert …
=> Add upsert option to upload/update

.github/workflows/ci.yml, .github/workflows/deploy-docs.yml
Update build pipeline for tests and gh pages
GitHub pages fail to build
GitHub pages should now build
=> update ci pipeline to include python 3.12 in tests

storage3/_async/client.py, storage3/_sync/client.py
- Add `follow_redirects=True`.
- All other Supabase libs follow redirects by default.
=> Follow redirects

storage3/_async/client.py, storage3/_sync/client.py
=> feat: Proxy support

storage3/_async/file_api.py, storage3/_sync/file_api.py
It removes the `BucketActionsMixin` from the `Bucket`, there is no documented way of using the library this way which makes this a bug.
Feel free to include screenshots if it includes visual changes.
=> feat: Buckets no longer have methods on them

storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py
- Add search param to the list buckets method
- Implement the download param correctly in the `create_signed_url`, `create_signed_urls` and `get_public_url` methods
Feel free to include screenshots if it includes visual changes.
=> fix: add search params to list buckets method

storage3/_async/file_api.py, storage3/_sync/file_api.py, tests/_async/test_client.py, tests/_sync/test_client.py
Bug fix
Feel free to include screenshots if it includes visual changes.
=> fix: add correct return data for upload to signed url

storage3/_async/bucket.py, storage3/_async/file_api.py, storage3/_sync/bucket.py, storage3/_sync/file_api.py, storage3/exceptions.py
Add new error class with better exception message handling
Current exception returns a string formatted as json which will require `json.loads` to access its properties.
The new error class returns an object which has a `to_dict` property that will return a dictionary of `code, message and status` for easier access to the values individually.
This PR should fix https://github.com/supabase/supabase-py/issues/726
=> feat: add new storage error class

storage3/_async/file_api.py, storage3/_sync/file_api.py
Bug fix
Returning Response as response type
Returning UploadResponse as response type
https://github.com/supabase/supabase-py/issues/1016
=> fix: incorrect upload return type

storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py, tests/_async/conftest.py, tests/_async/test_client.py, tests/_sync/conftest.py, tests/_sync/test_client.py
- Add custom metadata on upload
- Fix warnings tests were giving with pytest-asyncio
Custom Metadata
Adds support for custom metadata on objects:
```py
storage.from_(bucketName).upload(uploadPath, file, {
"metadata": {
"custom": "metadata",
"second": "second",
"third": "third",
},
})
```
Relates to [supabase/storage#439](https://github.com/supabase/storage/issues/439)
https://github.com/supabase/storage-py/issues/295
https://github.com/supabase/storage-js/pull/207
=> feat: add custom-metadata to upload

storage3/_async/file_api.py, storage3/_sync/file_api.py
Bug fix
`.exists` method is raising an exception when a file is not found
`.exists` method is returning false when a file is not found
=> fix: exists method raises error when no file found

Makefile, storage3/__init__.py, tests/_async/test_bucket.py, tests/_async/test_client.py, tests/_sync/test_bucket.py, tests/_sync/test_client.py, tests/test_client.py, tests/test_exceptions.py
Add more test coverage
Feel free to include screenshots if it includes visual changes.
=> chore(tests): add more test coverage

storage3/_async/file_api.py, storage3/_sync/file_api.py, storage3/types.py, tests/_async/test_client.py, tests/_sync/test_client.py
Bug fix with backward compatibility
The returned data keys deviate from that of the docs and the JS lib.
The returned data keys now match the docs and JS lib.
=> fix: add correct naming for returned data keys

.github/workflows/ci.yml, Makefile, README.md, poetry.lock, pyproject.toml, storage3/_async/bucket.py, storage3/_async/client.py, storage3/_async/file_api.py, storage3/_sync/bucket.py, storage3/_sync/client.py, storage3/_sync/file_api.py, storage3/utils.py, tests/_async/test_client.py, tests/_sync/test_client.py, tests/test_client.py, tests/test_utils.py, tests/utils.py
Allow developers to supply their own httpx client
Httpx client isn't very configurable and has limited options available for the developer
Httpx client can now be configured by the developer and be supplied to the storage library
=> feat: allow injection of httpx client

storage3/types.py
Bug fix for missing `type` field in `BaseBucket`. I didn't dig more than that.
When listing buckets, raise TypeError:
Returns my bucket list as expected:
Found this issue in self-hosted environment when upgrading `supabase/storage-api` from `v1.24.7` to `v1.25.9`
=> fix: add optional type field to bucket metadata

tests/_async/test_client.py, tests/_sync/test_client.py
Remove trailing `;` from tests, that was changed in the newest storage-api version. 
This got changed in between I commited https://github.com/supabase/storage-py/commit/c4a81fb9f7acacf8dccbf579daf4030200d8ab20 and when it was merged to master, causing it to break the CI tests. I believe it might be supabase cli version `2.34.2` (that bumped the storage-api version) that caused the change this.
=> fix: remove extraneous char in test
